<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>

<?php $_product = $this->getProduct(); ?>
<?php $themeHelper = $this->getThemeHelper(); ?>
<?php $themeSettings = $themeHelper->getThemeSettings(); ?>
<?php $_imagehelper = $this->getImageHelper(); ?>
<?php $quickViewHelper = $this->getQuickViewHelper(); ?>
<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
<?php $_helper = $this->getCatalogHelperOutput(); ?>
<?php $image = 'category_page_grid'; ?>
<?php $lazyLoad = $this->getLazyLoad(); ?>
<?php $lazyImg = $this->getLazyLoadBaseImage(); ?>
<?php 
/* Product Data */
$productUrl = $_product->getProductUrl();
?>
<div class="product-item-info" data-container="product-grid">
    <?php
        $size = $this->getSize();
        $productImageFirst = $productImage = $_imagehelper->init($_product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
		
		if($lazyLoad){
			$productImageFirst = $lazyImg;
		}
    ?>
    <?php // Product Image ?>
    <div class="product-item-image<?php if($lazyLoad): ?> lazy-img<?php endif ?>">
        <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $this->getPadding(); ?>;" class="product photo product-item-photo" tabindex="-1">
        
            <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
                
            <img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy product-image-photo"  data-src="<?php echo $productImage ?>"/>
			
			<span class="product-image-photo"></span>
        </a>
        <?php // Product Label ?>
		<?php echo $themeHelper->getProductLabel($_product) ?>
		
		<?php if ($this->getWishList()): ?>
		<div data-role="add-to-links" class="action-wishlist">
			<a href="#"
			   class="action towishlist"
			   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
			   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
			   data-post='<?php /* @escapeNotVerified */ echo $this->getWishListPost(); ?>'
			   data-action="add-to-wishlist"
			   role="button">
				<span class="icon"></span>
			</a>
		</div>
		<?php endif; ?>
    </div>
    <div class="product details product-item-details">
        <h5 class="product name product-item-name">
            <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $productUrl ?>">
                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
            </a>
        </h5>
		
		<?php if($this->getSwatches()): ?>
		<div class="product-buy_info">
			<?php echo $this->getSwatches(); ?>
		</div>
		<?php endif ?>
		
		<?php echo $this->getPrdPrice() ?>
        
        <?php echo $this->getReview(); ?>
        
		<div class="product actions product-item-actions">
			<?php if ($_product->isSaleable()): ?>
				<div class="actions-primary<?php if(!$this->getCompare()): ?> no-compare<?php endif ?>">
					<?php $postParams = $this->getPostParams(); ?>
					<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
						<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
						<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
						<?php echo $this->getFk(); ?>
						<button type="submit"
								title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
								class="action tocart primary">
							<span class="ion ion-ios-cart"></span>
						</button>
					</form>
				</div>
			<?php endif; ?>
			
			<div class="actions-quickview"><?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?></div>
			
			<?php if($this->getCompare()): ?>
			<div data-role="add-to-links" class="actions-compare">
				<a href="#"
				   class="action tocompare"
				   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				   role="button">
					<i class="ion-ios-shuffle-strong"></i>
				</a>
			</div>
			<?php endif ?>
		</div>
    </div>
</div>