<?php $_product = $this->getProduct() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php  ?>
<div class="content-block single-product">
	<?php if($this->hasData('mgs_panel_title') || $this->hasData('mgs_panel_note')): ?>
		<?php if($this->getData('mgs_panel_title') != null || $this->getData('mgs_panel_note') != null): ?>
			<div class="content-heading">
				<?php if($this->hasData('mgs_panel_title') && $this->getData('mgs_panel_title') != null): ?>
					<h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
				<?php endif ?>
				<?php if($this->hasData('mgs_panel_note') && $this->getData('mgs_panel_note') != null): ?>
					<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
				<?php endif ?>
			</div>
		<?php endif ?>
	<?php endif ?>
	
	<?php if ($_product && $_product->getId()): ?>
		<?php 
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
			$image = 'category_page_grid';
			$image_hover = 'product_base_image';
			$themeSettings = $themeHelper->getThemeSettings();			
		?>
		
		<div class="block widget mgs-product products-grid">
			<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
			<div class="product-item-info" data-container="product-grid">
				<?php
					$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
					$size = $themeHelper->getImageSize($this->getRatio());
					$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
					$productImageHover = $_imagehelper->init($_product, $image_hover)->resize($size['width'], $size['height'])->getUrl();	
				?>
				<div class="row">
					<div class="product-top c0l-lg-6 col-md-12 col-sm-12">
						<?php // Product Image ?>
						<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<img src="<?php echo $productImage; ?>" data-small="<?php echo $productImage ?>" data-base="<?php echo $productImageHover ?>" alt="<?php echo $_productNameStripped ?>" class="img-fluid product-image-photo "/>
						</a>	
					</div>
					<div class="product-top-detail col-lg-6 col-md-12 col-sm-12">
						<?php if($this->getProductName()): ?>
							<h5 class="product name product-item-name">
								<a class="product-item-link"
								   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>	
								</a>
							</h5>
						<?php endif ?>
						<!-- Show Product Price -->
						<?php if($this->hasData('product_price') && $this->getData('product_price')): ?>
							<?php echo $block->getProductPrice($_product) ?>
						<?php endif ?>
						<!-- Show Short Description -->
						<?php if($this->hasData('product_description') && $this->getData('product_description')): ?>
							<?php if($this->hasData('characters_count') && ($this->getData('characters_count')!='') && ($this->getData('characters_count')>0)): ?>
								<?php $description = $themeHelper->truncate($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), $this->getData('characters_count'))?>
							<?php else: ?>
								<?php $description = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')?>
							<?php endif ?>
							<div class="product description"><?php echo $description ?></div>
						<?php endif ?>
						<?php if($this->getProductAddcart() && $_product->isSaleable()): ?>
							<?php $postParams = $block->getAddToCartPostParams($_product); ?>
							<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
								<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
								<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
								<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
								<button type="submit"
										title="<?php /* @escapeNotVerified */ echo __('Add To Cart') ?>"
										class="action primary tocart"
										id="product-addtocart-button">
									<span class="text"><?php /* @escapeNotVerified */ echo __('Add To Cart') ?></span>
								</button>
							</form>
						<?php endif ?>
						<?php if($this->getProductRating()): ?>
							<?php $product = $this->getLoadProduct($_product->getId()) ?>
							<?php echo $block->getReviewsSummaryHtml($product, $templateType, true); ?>
						<?php endif ?>	
					</div>
				</div>
			</div>
		</div>
		
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no product matching the selection.') ?></div>
	<?php endif ?>
</div>