<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$helper =  \Magento\Framework\App\ObjectManager::getInstance()->get('MGS\Mpanel\Helper\Data');
$url = $helper->getCssUrl();
$canUsePanel = $helper->acceptToUsePanel();
$hAbs = $helper->getStoreConfig('mgstheme/header/absolute_header');
$miniCart = $helper->getStoreConfig('mpanel/minicart/minicart_type');
$classMiniCart = $miniCart == 2 ? 'sidebar_cart' : 'dropdown_cart';
?>
<!doctype html>
<html class="<?php echo $classMiniCart ?> use-<?php echo $helper->getHeaderClass() ?><?php if($hAbs): ?> absolute_header<?php endif ?>" <?php /* @escapeNotVerified */ echo $htmlAttributes ?>>
    <head <?php /* @escapeNotVerified */ echo $headAttributes ?>>
		<script>
			var RTL = false;
			var WEB_URL = "<?php echo $helper->getUrlBuilder()->getUrl() ?>";
			var CATALOG_AJAX = "<?php echo $helper->getStoreConfig('mgstheme/general/catalog_ajax'); ?>";
		</script>
        <?php /* @escapeNotVerified */ echo $requireJs ?>
        <?php /* @escapeNotVerified */ echo $headContent ?>
        <?php /* @escapeNotVerified */ echo $headAdditional ?>
		<?php //echo $helper->getLinksFont() ?>
        <?php if($canUsePanel): ?>
            <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet"> 
        <?php endif ?>
		<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $helper->getMediaUrl() ?>mgs/css/<?php echo $helper->getStore()->getId() ?>/custom_config.css" /> 
		<?php if($helper->showButton()): ?>
		<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $helper->getPanelCssUrl() ?>" /> 
		<?php endif ?>
		
    </head>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?php /* @escapeNotVerified */ echo $loaderIcon; ?>"}}' <?php /* @escapeNotVerified */ echo $bodyAttributes ?>>

		<?php if($helper->showButton() && !$helper->isPopup()): ?>
			<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Panel\Toppanel')->setTemplate('panel/toppanel.phtml')->setCacheable(false)->toHtml() ?>
		<?php endif ?>
		
		<?php if($helper->acceptToUsePanel() && ($helper->isHomepage() || $helper->isCmsPage())): ?>
			<?php echo $helper->convertContent($layoutContent, $this->getLayout()->createBlock('MGS\Mpanel\Block\Panel\HomeContent')->setTemplate('panel/homecontent.phtml')->toHtml()) ?>
		<?php else: ?>
			<?php echo $helper->convertContent($layoutContent, "") ?>
		<?php endif ?>
		
		<?php if($canUsePanel): ?>
			<script  type="text/javascript" src="<?php echo $this->getViewFileUrl('MGS_Mpanel::js/panel.js') ?>"></script>
		<?php endif ?>
        
    </body>
</html>
