<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$post = $block->getCurrentPost();
$showAction = $this->getConfig('general_settings/show_action');
?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank5.png'); ?>
<div class="blog-post blog-main-info">
	<?php if($helper->getImageThumbnailPost($post) != ""): ?>
		<div class="post-images">
			<div class="post-images">
				<?php if($helper->getImageThumbnailPost($post) != ""): ?>
					 <?php 
						if(!$lazyLoad){
							$baseImage = $this->getImageThumbnailPost($post);
						}
						?>
                        <div class="post-thumbnail <?php if($lazyLoad): ?> lazy-img<?php endif ?>">
							
							<a class="post-thumbnail--image " style="background-image:url('<?php echo $helper->getImageThumbnailPost($post); ?>');" href="<?php echo $post->getPostUrlWithNoCategory(); ?>" title="<?php echo $post->getTitle(); ?>">
								<img class="img-fluid lazy" src="<?php echo $baseImage; ?>" data-src="<?php echo $helper->getImageThumbnailPost($post); ?>" alt="<?php echo $post->getTitle(); ?>" />
							</a>
                            <?php if($post->getThumbType() == "video" && $post->getVideoThumbId() != ""): ?>
								<a class="btn btn-primary popup-video" href="<?php echo $helper->getVideoThumbUrl($post); ?>"><?php echo __('Watch Video'); ?></a>
                            <?php endif ?>
                        </div>
					
				<?php endif ?>
			</div>
		</div>
	<?php endif ?>
    <?php if ($post->getContent()): ?>
        <div class="row post-content">
            <div class="col-lg-10 col-md-10 col-sm-12 offset-xl-1 offset-lg-1 offset-md-1 offset-sm-1 post-short-description">
				<div class="post-metas-share margin-bottom40">
					<div class="post-metas">
						<div class="meta-date">
							<i class="fa fa-calendar"></i>
							<span>
								<?php echo __('%1', $block->formatDate($post->getUpdatedAt(), \IntlDateFormatter::MEDIUM, false)); ?>
							</span>
						</div>
						<div class="meta-author ">
							<span>By</span>
							<span class="color-theme">
								<?php echo __('%1', $post->getUser()); ?>
							</span>
						</div>
					</div>
					<?php if($helper->getStoreConfig('mpanel/share_config/enabel_share') && $helper->getStoreConfig('mpanel/share_config/share_blog_detail')): ?>
						<div class="share-this">
							<span class="title"><?php echo __('Share This:'); ?></span>
							<?php echo $block->getChildHtml('blog.detail.sharethis'); ?>
						</div>
					<?php endif ?>
				</div>
				<div class="content-blog">
					<?php echo $helper->generateContentFilter($post->getContent()); ?>
				</div>
            </div>
        </div>
    <?php endif; ?>
	
    <?php if ($block->getGalleryImage($post)): ?>
        <div class="gallery-image-carousel owl-carousel margin-top70">
            <?php foreach($block->getGalleryImage($post) as $_img): ?>
                <a class="gallery_image" href="<?php echo $_img; ?>">
                    <img src="<?php echo $_img; ?>" alt="" class="img-fluid"/>
                </a>
            <?php endforeach ?>
        </div>
        <script type="text/javascript">
            require([
                'jquery',
                'mgs/owlcarousel'
            ], function(jQuery){
                (function($) {
                    $(".gallery-image-carousel").owlCarousel({
                        items: 1,
                        loop: true,
                        nav: true,
                        dots: false,
                        autoHeight: true,
                        autoplay: false,
                        autoplayHoverPause: false,
                        rtl: RTL,
                        navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
                        responsive:{
                            0:{
                                nav: false,
                                dots: true
                            },
                            768:{
                                nav: true,
                                dots: false
                            }
                        },
                    });
                })(jQuery);
            });
            
            require([
                'jquery',
                'magnificPopup'
            ], function(jQuery){
                (function($) {
                    $(document).ready(function() {
                        $('.gallery-image-carousel').magnificPopup({
                            delegate: '.owl-item:not(.cloned) a',
                            type: 'image',
                            tLoading: 'Loading image #%curr%...',
                            mainClass: 'mfp-img-gallery',
                            fixedContentPos: true,
                            gallery: {
                                enabled: true,
                                navigateByImgClick: true,
                                preload: [0,1]
                            },
                            image: {
                                tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
                                titleSrc: function(item) {
                                return item.el.attr('title');
                                }
                            }
                        });
                    });
                })(jQuery);
            });
        </script>
    <?php endif ?>	
	
	<?php if($showAction): ?>
		<div class="post-actions">
			<?php $prevPost = $this->getPrevPost($post->getId()); ?>
			<?php if($post->getId() != $prevPost['id']): ?>
				<div class="prev-action action"><a href="<?php echo $prevPost['url']; ?>"><?php echo __('Previous'); ?></a></div>
			<?php endif ?>
			<?php $nextPost = $this->getNextPost($post->getId()); ?>
				<?php if($post->getId() != $nextPost['id']): ?>
				<div class="next-action action"><a href="<?php echo $nextPost['url']; ?>"><?php echo __('Next'); ?></a></h4></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
    <div class="row">
        <div class="col-md-12 col-md-push-2 col-sm-12 col-xs-12">
            <?php echo $block->getChildHtml('post_view_comment'); ?>
        </div>
    </div>
</div>
