<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
		<div class="block-title filter-title">
			<div class="container">
				<strong><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
				<?php if ($block->getLayer()->getState()->getFilters()): ?>
					<div class="block-actions filter-actions">
						<a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
					</div>
				<?php endif; ?>
			</div>
		</div>

		<div class="block-content filter-content">
			<div class="container">
				<?php echo $block->getChildHtml('state') ?>

				<?php if ($block->getLayer()->getState()->getFilters()): ?>
					<div class="block-actions filter-actions">
						<a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
					</div>
				<?php endif; ?>
				<div class="filter-wrapper">
				<?php $wrapOptions = false; ?>
				<?php foreach ($block->getFilters() as $filter): ?>
					<?php if (!$wrapOptions): ?>
						<strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
						<div class="filter-options" id="narrow-by-list">
					<?php $wrapOptions = true; endif; ?>
						<?php if ($filter->getItemsCount()): ?>
							<div class="filter-item">
								<div role="heading" aria-level="3" class="filter-options-title"><?php echo $block->escapeHtml(__($filter->getName())) ?></div>
								<div class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
							</div>
						<?php endif; ?>
				<?php endforeach; ?>
				<?php if ($wrapOptions): ?>
					</div>
				<?php endif; ?>
				</div>
			</div>
		</div>
    </div>
<?php endif; ?>
