<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $themeHelper->acceptToUsePanel() ?>

<?php // Get footer version ?>
<?php $footer = $themeHelper->getStoreConfig('mgstheme/footer/footer'); ?>
<?php if($footer == 'footer' || $footer == ""): ?><?php $footer = 'footer_1'; ?><?php endif ?>
<?php // Footer content ?>
<div class="footer-container">
    <?php // Footer 1 ?>
    <?php if($footer == 'footer_1'): ?>
        <div class="footer-container">
            <div class="middle-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_about_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block2')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_newsletter')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bottom-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php elseif($footer == 'footer_2'): ?>
        <div class="footer-container">
            <div class="top-footer">
                <div class="container">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_newsletter')->setCanUsePanel($canUsePanel)->toHtml() ?>
                </div>
            </div>
            <div class="middle-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_about_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block2')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block3')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bottom-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif ?>
</div>